# Generated by cucumber-sinatra. (2015-01-15 14:18:18 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/FileWeightWatchers.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = FileWeightWatchers

class FileWeightWatchersWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  FileWeightWatchersWorld.new
end
